Repository wearesho-team/yii2-phonet, pull requests merged in 2019-03, with the labels that each got.

#1 Implementation
  .env.example
  .gitignore
  .travis.yml
  README.md
  composer.json
  composer.lock
  phpunit.xml
  src/Bootstrap.php
  src/Call/Pause.php
  src/Call/Type.php
  src/Controller.php
  src/Identity.php
  src/IdentityInterface.php
  src/IdentityTrait.php
  src/Job/Call/Complete/Receive.php
  src/Migrations/M190220115948CreateEmployeeTable.php
  src/Migrations/M190221131201CreateCallTable.php
  src/Migrations/M190223120059CreateCompleteCallTable.php
  src/Migrations/M190226094729CreateCallInternalTable.php
  src/Migrations/M190226133740CreateCallExternalTable.php
  src/Record/Call.php
  src/Record/Call/Complete.php
  src/Record/Call/External.php
  src/Record/Call/Internal.php
  src/Record/Employee.php
  tests/Mock/User.php
  tests/Unit/BootstrapTest.php
  tests/Unit/ControllerTest.php
  tests/Unit/Job/Call/Complete/Receive/RepositoryExceptionLogTest.php
  tests/Unit/Job/Call/Complete/ReceiveTest.php
  tests/Unit/Job/Call/Complete/TestCase.php
  tests/Unit/Record/CallTest.php
  tests/Unit/Record/EmployeeTest.php
  tests/Unit/Record/External/DataTest.php
  tests/Unit/Record/Internal/DataTest.php
  tests/Unit/TestCase.php
  tests/autoload.php
  tests/bootstrap.php
  tests/config.php
  tests/constants.php
  yii
Labels: enhancement, help wanted

#3 Fix dependencies
  .gitignore
  composer.json
  composer.lock
Labels: bug

#5 Remove excess http exception from client requests
  src/Controller.php
  src/IdentityInterface.php
  src/IdentityTrait.php
  tests/Mock/User.php
Labels: enhancement

#4 Fix alias definition
  src/Bootstrap.php
  src/Controller.php
  src/Record/Call.php
  src/Record/Employee.php
  tests/Unit/BootstrapTest.php
Labels: bug

#6 Fix foreign key for internal call table, fix controller logic
  src/Controller.php
  src/Migrations/M190226094729CreateCallInternalTable.php
Labels: bug

#7 Add logging errors
  src/Controller.php
Labels: enhancement

#8 Fix convert updated_at and dial_at attributes
  composer.json
  composer.lock
  src/Controller.php
  src/Job/Call/Complete/Receive.php
  src/Migrations/M190327164112FixExternalCallColumns.php
  src/Record/Call.php
  src/Record/Call/External.php
  tests/Unit/ControllerTest.php
  tests/Unit/Record/CallTest.php
Labels: bug

#9 Update phonet package version to latest
  composer.json
  composer.lock
Labels: enhancement
